image:
  file: .gitpod.Dockerfile

tasks:
  - before: >
      mkdir /workspace/opt-pulumi &&
      sudo ln -s /workspace/opt-pulumi /opt/pulumi
    init: >
      make ensure &&
      make install &&
      pulumi login &&
      make
